[manifest]
dump_lua = true
priority = 2147483643 # 2147483647 - 4
version = "1.0.0"

# Update self ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''st:setUpdate(function(self, dt)'''
payload = '''
	utilitools.files.beattools.livelyCranky.update()
'''
position = "after"
target = "states/Editor.lua"
times = 1
