[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

# Bounce dragging ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''self.overlappingEvents = {}'''
payload = '''
local prevOverlapping = self.overlappingEvents
local prevBounceSelect = self.bounceSelected
local prevBounceSelectTime = self.bounceSelectTime
self.bounceSelected = false
self.bounceSelectTime = 0
self.bounceSelectAccumulation = 0
'''
position = "before"
target = "states/Editor.lua"
times = 1

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''-- check end of holds as well'''
payload = '''
-- check bounces of bounces as well
if mods.beattools.config.bounceDragging and v.type == "bounce" and (v.bounces or 1) > 0 and ((not mods.beattools.config.fakeRepeat) or v.beattoolsRepeatChild == nil) and not ({ ghost = true, hide = true })[utilitools.files.beattools.eventGroups.eventVisibility(v)] then
	for ii = 1, (v.bounces or 1) do
		local pos2 = self:getPosition((mods.beattools.config.displayEndAngle and v.endAngle or v.angle) + (v.rotation or 0) * ii, v.time + (v.delay or 1) * ii)
		if ((not mods.beattools.config.fakeRepeat) or v.beattoolsRepeatChild == nil) and not ({ ghost = true, hide = true })[utilitools.files.beattools.eventGroups.eventVisibility(v)] and helpers.collide(
			{ x = mouse.rx, y = mouse.ry, width = 0, height = 0 },
			{ x = pos2[1] - 8, y = pos2[2] - 8, width = 16, height = 16 }) then
			if overlap then
				table.insert(overlap, i)
			else
				table.insert(self.overlappingEvents, { event = i, bounceSelected = ii })
			end
		end
	end
end
'''
position = "before"
target = "states/Editor.lua"
times = 2

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''for _, v in ipairs(holdEndSelection) do'''
payload = '''
if self.overlappingEvents[1].bounceSelected then
	self.bounceSelected = self.overlappingEvents[1].bounceSelected
	self.bounceSelectTime = love.timer.getTime()
	if prevOverlapping and #prevOverlapping == 1 and prevOverlapping[1].event == self.overlappingEvents[1].event and prevOverlapping[1].bounceSelected == self.overlappingEvents[1].bounceSelected and prevBounceSelectTime and prevBounceSelectTime ~= 0 and self.bounceSelectTime - prevBounceSelectTime <= 0.5 then
		self.bounceSelectTime = -1
		modlog(mods.beattools, "Double clicked bounce")
	end
end
'''
position = "before"
target = "states/Editor.lua"
times = 1

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if not self.holdEndSelected then
	mod.time = self.selectedEvent.time + beat'''
payload = '''
if mods.beattools.config.bounceDragging and self.bounceSelected then
	if mods.beattools.config.bounceDoubleClick and self.bounceSelectTime == -1 then
		self.bounceSelectAccumulation = self.bounceSelectAccumulation + beat
		if math.abs(self.bounceSelectAccumulation) >= (self.selectedEvent.delay or 1) then
			local bounceDiff = math.floor(self.bounceSelectAccumulation / (self.selectedEvent.delay or 1))
			mod.bounces = math.max(self.selectedEvent.bounces + bounceDiff, 1)
			self.bounceSelected = math.max(self.bounceSelected + bounceDiff, 1)
			self.bounceSelectAccumulation = self.bounceSelectAccumulation % (self.selectedEvent.delay or 1)
		end
	else
		-- If the user is holding a bounced bounce, we only move the rotation/delay.
		mod.rotation = (self.selectedEvent.rotation or 0) + angle / self.bounceSelected
		mod.delay = math.max((self.selectedEvent.delay or 1) + beat / self.bounceSelected, 0)
	end
elseif not self.holdEndSelected then
	mod.time = self.selectedEvent.time + beat
'''
position = "at"
target = "states/Editor.lua"
times = 1

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''local angle = self.cursorAngle

					if not self.holdEndSelected then'''
payload = '''
local angle = self.cursorAngle
if mods.beattools.config.bounceDragging and self.bounceSelected then
	if mods.beattools.config.bounceDoubleClick and self.bounceSelectTime == -1 then
		local timeDiff = self.cursorBeat - (self.selectedEvent.time + (self.selectedEvent.delay or 1) * self.bounceSelected)
		if math.abs(timeDiff) >= (self.selectedEvent.delay or 1) then
			local bounceDiff = math.floor(timeDiff / (self.selectedEvent.delay or 1))
			self.selectedEvent.bounces = math.max(self.selectedEvent.bounces + bounceDiff, 1)
			self.bounceSelected = math.max(self.bounceSelected + bounceDiff, 1)
			self.bounceSelectAccumulation = 0
		end
	else
		-- see next comment on what this does. - bliv - Penta
		angle = helpers.closestAngle(angle, self.selectedEvent.angle + (self.selectedEvent.rotation or 0) * self.bounceSelected)

		self.selectedEvent.rotation = (angle - self.selectedEvent.angle) / self.bounceSelected
		self.selectedEvent.delay = math.max(self.selectedEvent.delay + (self.cursorBeat - (self.selectedEvent.time + (self.selectedEvent.delay or 1) * self.bounceSelected)) / self.bounceSelected, 0)
	end
elseif not self.holdEndSelected then
'''
position = "at"
target = "states/Editor.lua"
times = 1
