[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

# Fake repeat and (un)tagging buttons ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if imgui.Button('Delete event') then'''
payload = '''
if self.selectedEvent and self.selectedEvent.type == "ease" and mods.beattools.config.easeCurrentValues then
	if beattools.easeList.unsorted.all[self.selectedEvent.var] ~= nil and self.selectedEvent.var ~= "outline" then
		local ease, count = utilitools.files.beattools.easing.getEase("ease", self.selectedEvent.var, cs.editorBeat, nil, nil)
		local ease2, count2 = utilitools.files.beattools.easing.getEase("ease", self.selectedEvent.var, self.selectedEvent.time, self.selectedEvent.order, utilitools.files.beattools.easing.getIndex(self.selectedEvent) - 1)
		local eventTime = ease2.value
		local editorTime = ease.value
		if mods.beattools.config.easeListRound then
			if type(eventTime) == "number" then
				eventTime = helpers.round(eventTime * 1e3) / 1e3
			end
			if type(editorTime) == "number" then
				editorTime = helpers.round(editorTime * 1e3) / 1e3
			end
		end
		imgui.Text(
			"Value at event time: " ..
			tostring(eventTime) ..
			"\nValue at editor beat: " ..
			tostring(editorTime)
		)
	else
		imgui.Text("Invalid Ease")
	end
	imgui.Separator()
end
if self.selectedEvent and mods.beattools.config.fakeRepeat and not utilitools.files.beattools.eventVisuals.hasRepeat[self.selectedEvent.type] then
	Event.property(self.selectedEvent, "int", "repeats", "Times to repeat", {optional = true, default = 0})
	if self.selectedEvent.repeats and self.selectedEvent.repeats > 0 then
		Event.property(self.selectedEvent, "decimal", "repeatDelay", "Beats between repeats", {step = cs:getBeatStep(), default = 1})
	else self.selectedEvent.repeatDelay = nil end
	if self.selectedEvent.repeats and self.selectedEvent.repeats > 0 and self.selectedEvent.repeatDelay and imgui.Button("Convert##beattools") then
		utilitools.prompts.confirm("Converting to real events will lose the functionality of changes of the main event cascading to repeated events", function ()
			utilitools.files.beattools.fakeRepeat.update(self.selectedEvent, true)
		end)
	end
	imgui.Separator()
end
if self.selectedEvent and mods.beattools.config.showEventGroups then
	utilitools.files.beattools.eventGroups.eventCustomGroup(self.selectedEvent)
end
if self.selectedEvent and mods.beattools.config.roundSelectedTimes then self.selectedEvent.time = helpers.round(self.selectedEvent.time * 1e3) / 1e3 end
if self.selectedEvent and mods.beattools.config.untaggingButtons then
	if imgui.Button('Change to tag') then
		self.changeToTagDialogue = true
		self.newTagName = ""
	end
	imgui.Separator()
end
if self.selectedEvent and mods.beattools.config.untaggingButtons and self.selectedEvent.type == "tag" then
	if imgui.Button("Untag") then
		self:beattoolsUntag({ self.selectedEvent })
	end
	imgui.SameLine()
	if imgui.Button("Untag same tag name") then
		utilitools.prompts.confirm("Continuing will untag all tags with the tag name \"" .. self.selectedEvent.tag .. "\"!", function ()
			self:beattoolsUntag({ self.selectedEvent.tag })
		end)
	end
	imgui.Separator()
end
'''
position = "before"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'decimal','repeatDelay', 'Beats between repeats', {step = cs:getBeatStep(),optional = true, default = 1})'''
payload = '''
if event.repeats and event.repeats > 0 then
	Event.property(event, 'decimal', 'repeatDelay', 'Beats between repeats', {step = cs:getBeatStep(), default = 1})
else event.repeatDelay = nil end
'''
position = "at"
target = "levelformat/events/Vfx/ease.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if imgui.Button('Delete selected events') then'''
payload = '''
if mods.beattools.config.untaggingButtons then
	if imgui.Button("Untag") then
		self:beattoolsUntag(self.multiselect.events)
	end
	imgui.SameLine()
	if imgui.Button("Untag same tag name") then
		local tempEvents = {}
		for i, v in ipairs(self.multiselect.events) do
			if v.type == "tag" then table.insert(tempEvents, v.tag) end
		end
		utilitools.prompts.confirm("Continuing will untag all tags with the same name as those in the selection!", function ()
			self:beattoolsUntag(tempEvents)
		end)
	end
	imgui.Separator()
end
'''
position = "before"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if #self.multiselect.events == 0 and #self.markers == 0 then'''
payload = '''
if mods.beattools.config.convertSingle and self.multiselect and #self.multiselect.events == 1 and #self.markers == 0 then
	local event = self.multiselect.events[1]
	self:noSelection()
	self.selectedEvent = event
end
if self.multiselect and #self.multiselect.events == 0 and #self.markers == 0 then
'''
position = "at"
target = "states/Editor.lua"

# Tagging but idk whats going on ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''self.changeToTagDialogue = true'''
payload = '''self.firstTimeTagDialogue = true'''
position = "after"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''self.newTagName = helpers.InputText("Tag name", self.newTagName, 9999)'''
payload = '''
if self.firstTimeTagDialogue then
	self.firstTimeTagDialogue = false
	imgui.SetKeyboardFocusHere()
end
'''
position = "before"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''self.cmd:executeNew(cmd.CreateEvent,{ type = 'tag', angle = 0, time = self.multiselectStartBeat, tag = self.newTagName, angleOffset = false })'''
payload = '''self.cmd:executeNew(cmd.CreateEvent,{ type = 'tag', angle = 0, time = self.multiselectStartBeat or self.selectedEvent.time, tag = self.newTagName, angleOffset = false })
self:deleteSelectedEvent()'''
position = "at"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if self.changeToTagDialogue and (not self.multiselect) then'''
payload = '''if self.changeToTagDialogue and (not (self.multiselect or self.selectedEvent)) then'''
position = "at"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''local tagEvents = helpers.copy(self.multiselect.events)'''
payload = '''local tagEvents = helpers.copy(self.multiselect and self.multiselect.events or { self.selectedEvent })'''
position = "at"
target = "states/Editor.lua"
