[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

# Hide menus ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''self:imgui()'''
payload = '''
if not beattoolsRecordPosition then self:imgui() beattools.randomizeWindows = false end
'''
position = "at"
target = "states/Editor.lua"

# Combo adjust ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if imgui.BeginCombo(imguiUniqueName, event[propertyName]) then'''
payload = '''if imgui.BeginCombo(imguiUniqueName, event[propertyName], mods.beattools.config.betterCombo and 2^4 + 2^5 + 2^7 or nil) then'''
position = "at"
target = "obj/GameManager.lua"

# Ctrl + i menu resize ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''9999)'''
payload = '''9999, mods.beattools.config.fullSize and "max" or nil)'''
position = "at"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''function helpers.InputTextMultiline(label, text, size)'''
payload = '''
function helpers.InputTextMultiline(label, text, size, size2)
	if size2 ~= nil and size2:sub(1, 3) == "max" then
		local lines = 1
		for _ in text:gmatch("\n") do
			lines = lines + 1
		end
		size2 = imgui.ImVec2_Float(
			utilitools.imguiHelpers.getWidth(label) - (size2 == "maxTooltip" and (not mods.beattools.config.hideHelpMarkers) and 29 or 0),
			imgui.GetFontSize() * lines + 6
		)
	end
'''
position = "at"
target = "lib/imguihelper.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''imgui.InputTextMultiline(label, buffer, size)'''
payload = '''imgui.InputTextMultiline(label, buffer, size, size2)'''
position = "at"
target = "lib/imguihelper.lua"

# Input resize ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''local enabled = true'''
payload = '''
local label = mods.beattools.config.shortenParams and mods.beattools.config.keysWhiteList[imguiUniqueName] ~= true and mods.beattools.config.keysWhiteList[imguiUniqueName] or (((propertyType == 'decimal') or (propertyType == 'int')) and propertyName or imguiUniqueName)
local length = utilitools.imguiHelpers.getWidth(imguiUniqueName) - ((not mods.beattools.config.hideHelpMarkers) and 29 or 0)
'''
position = "after"
target = "obj/GameManager.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''imgui.PushItemWidth(100)'''
payload = '''if not mods.beattools.config.fullSize then imgui.PushItemWidth(mods.beattools.config.inputSize) else imgui.PushItemWidth(length) end'''
position = "at"
target = "obj/GameManager.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
local truncatedResult = math.floor(1000*result+0.5)/1000
local truncatedProperty = math.floor(1000*propertyOld+0.5)/1000
'''
payload = '''
local precision = mods.beattools.config.preciseTimeInput and imguiUniqueName == "time" and 1e12 or 1e3
local truncatedResult = math.floor(precision * result + 0.5) / precision
local truncatedProperty = math.floor(precision * propertyOld + 0.5) / precision
'''
position = "at"
target = "obj/GameManager.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''imgui.Text(propertyName)'''
payload = '''imgui.Text(utilitools.imguiHelpers.visibleLabel(label))'''
position = "at"
target = "obj/GameManager.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''numptr = ffi.new('char[' .. propertyLength .. ']', string.format("%.3f", event[propertyName]))'''
payload = '''numptr = ffi.new('char[' .. propertyLength .. ']', string.format(mods.beattools.config.preciseTimeInput and imguiUniqueName == "time" and "%.12f" or "%.3f", event[propertyName]))'''
position = "at"
target = "obj/GameManager.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''imgui.PushItemWidth(60)'''
payload = '''if not mods.beattools.config.fullSize then imgui.PushItemWidth(mods.beattools.config.inputSize) else imgui.PushItemWidth(length * 1 - 4 * 2 - 19 * 2 + imgui.GetStyle().ItemInnerSpacing.x - imgui.GetStyle().ItemSpacing.x) end -- Penta: these values are hard coded in the parser lol'''
position = "at"
target = "obj/GameManager.lua"

[[patches]]
[patches.regex]
pattern = '''imguiUniqueName, (?<param>numptr|event)'''
payload = '''label, $param'''
position = "at"
target = "obj/GameManager.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
	cs.cmd:executeNew(cmd.ModifyKeys,event,{[propertyName] = newval})
end

helpers.imguiHelpMarker(tooltip)'''
payload = '''
	cs.cmd:executeNew(cmd.ModifyKeys,event,{[propertyName] = newval})
end

if mods.beattools.config.hideHelpMarkers then
	utilitools.imguiHelpers.tooltip(tooltip)
else helpers.imguiHelpMarker(tooltip) end
'''
position = "at"
target = "obj/GameManager.lua"

# Charter fix ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if not self.variant then
	self.level.metadata.charter = helpers.InputText("Charter", self.level.metadata.charter, 9999)
else'''
payload = '''
if mods.beattools.config.browserCharter or (not self.variant) then
	self.level.metadata.charter = self.level.metadata.charter or ""
	self.level.metadata.charter = helpers.InputText("Charter", self.level.metadata.charter, 9999)
	helpers.imguiHelpMarker("This is the name that will be displayed on the Beatblock Browser.")
end
if self.variant then
'''
position = "at"
target = "states/Editor.lua"

[[patches]]
[patches.regex]
pattern = '''self\.variant = \{ ?name = self\.newVariantName, display = self\.newVariantName, difficulty = 0, charter = '',slot ?=0 ?\}'''
payload = '''self.variant = { name = self.newVariantName, display = self.newVariantName, difficulty = 0, charter = mods.beattools.config.charter }'''
position = "at"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''charter = 'Charter','''
payload = '''charter = mods.beattools.config.charter,'''
position = "at"
target = "obj/LevelManager.lua"

# Bookmark ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
local prevBookmarkBeat = 0
local currBookmarkBeat = 0
'''
payload = '''
local prevBookmarkBeat = self.smallestBeat - (mods.beattools.config.scrollPast == 0 and 1 or mods.beattools.config.scrollPast)
local currBookmarkBeat = prevBookmarkBeat
local prevSectionName = "Start"
'''
position = "at"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''prevBookmarkBeat = v.time'''
payload = '''prevSectionName = v.name'''
position = "after"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''return prevBookmarkBeat, currBookmarkBeat, nextBookmarkBeat, sectionName'''
payload = '''return prevBookmarkBeat, currBookmarkBeat, nextBookmarkBeat, sectionName, prevSectionName'''
position = "at"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''local prevBookmarkBeat, currBookmarkBeat, nextBookmarkBeat, sectionName = self:findBookmarkBeats()'''
payload = '''local prevBookmarkBeat, currBookmarkBeat, nextBookmarkBeat, sectionName, prevSectionName = self:findBookmarkBeats()'''
position = "at"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''local cAngle = 2 * math.pi * (self.editorBeat - currBookmarkBeat) / (nextBookmarkBeat - currBookmarkBeat)'''
payload = '''local cAngle = 2 * math.pi * (self.editorBeat - currBookmarkBeat) / (nextBookmarkBeat - currBookmarkBeat ~= 0 and nextBookmarkBeat - currBookmarkBeat or 1)'''
position = "at"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''love.graphics.printf(sectionName, project.res.cx - 499, project.res.cy - 60, 1000, "center")'''
payload = '''
local bookmark, bookmarkC = utilitools.files.beattools.easing.getEase("bookmark", nil, cs.editorBeat, nil, nil)
love.graphics.printf((mods.beattools.config.betterBookmarks and bookmarkC.index ~= 0 and self.editorBeat == bookmarkC.event.time and prevSectionName .. " >> " or "") .. sectionName .. (mods.beattools.config.betterBookmarks and " (" .. bookmarkC.index .. "/" .. bookmarkC.total .. ")" or ""), project.res.cx - 499, project.res.cy - 60, 1000, "center")
if mods.beattools.config.betterBookmarks and bookmark.description ~= nil and bookmark.description ~= "" then
	love.graphics.printf(bookmark.description, project.res.cx - 499, project.res.cy + 60 - 10, 1000, "center")
end
'''
position = "at"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''love.graphics.circle("fill", project.res.cx, project.res.cy, self:beatToRadius(self.editorBeat))'''
payload = '''
love.graphics.circle("fill", project.res.cx, project.res.cy, self:beatToRadius(self.editorBeat))
if mods.beattools.config.betterBookmarks then
	love.graphics.setColor(love.math.colorFromBytes(bookmark.r, bookmark.g, bookmark.b, 255))
	love.graphics.arc("line", "open", project.res.cx, project.res.cy, self:beatToRadius(self.editorBeat), 0, 2 * math.pi, 100)
end
'''
position = "at"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''local textWidth = love.graphics.getFont():getWidth(tostring(math.floor(self.editorBeat)))
love.graphics.draw(sprites.editor.beaticon, project.res.cx - textWidth / 2 - 5.5, project.res.cy - 5)'''
payload = '''
local beatText = tostring(math.floor(self.editorBeat))
local easingPrevBookmarkTime = bookmarkC.index == 0 and 0 or bookmarkC.event.time
local bookmarkBeatText = math.floor(self.editorBeat - easingPrevBookmarkTime) .. "/" .. math.floor(nextBookmarkBeat - easingPrevBookmarkTime)
local textWidth = love.graphics.getFont():getWidth(beatText)
local bookmarkBeatTextWidth = love.graphics.getFont():getWidth(bookmarkBeatText)

if mods.beattools.config.betterBookmarks then
	love.graphics.setColor(love.math.colorFromBytes(bookmark.r, bookmark.g, bookmark.b, 255))
	love.graphics.draw(sprites.editor.bookmarkicon, project.res.cx - bookmarkBeatTextWidth / 2 - 5.5, project.res.cy - 5 + 11)
end
'''
position = "at"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''love.graphics.printf(math.floor(self.editorBeat), project.res.cx - 18.5, project.res.cy - 7, 50, "center")'''
payload = '''
love.graphics.printf(beatText, project.res.cx - 18.5, project.res.cy - 7, 50, "center")
if mods.beattools.config.betterBookmarks then love.graphics.printf(bookmarkBeatText, project.res.cx - 18.5, project.res.cy - 7 + 11, 50, "center") end
'''
position = "at"
target = "states/Editor.lua"

# Suggest ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'string', 'var', 'Variable to ease (must be a child of cs)', {default = ''})'''
payload = '''event.var = utilitools.suggest.suggest(event.var, beattools.easeList.eases)'''
position = "after"
target = "levelformat/events/Vfx/ease.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'string', 'var', 'Variable to set (must be a child of cs)', {default = ''})'''
payload = '''event.var = utilitools.suggest.suggest(event.var, beattools.easeList.bools)'''
position = "after"
target = "levelformat/events/Vfx/setBoolean.lua"

# Menu in editor ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if self.goToBeatDialogue then'''
payload = '''
if true then
	if mods.beattools.config.showEventGroups and utilitools.files.beattools.eventGroupWindow then
		utilitools.files.beattools.eventGroupWindow(window_flag, inputFlag)
	end
	if mods.beattools.config.easeList and utilitools.files.beattools.easeList then
		utilitools.files.beattools.easeList(window_flag, inputFlag)
	end
	if mods.beattools.config.bookmarkList and utilitools.files.beattools.bookmarkList then
		utilitools.files.beattools.bookmarkList(window_flag, inputFlag)
	end
	if mods.beattools.config.editorMenu or mods.beattools.config.colorPreview or mods.beattools.config.coordsDisplay then
		helpers.SetNextWindowPos(750, 420, window_flag)
		helpers.SetNextWindowSize(200, 300, window_flag)
		if imgui.Begin("Beattools", nil, inputFlag) then

			if mods.beattools.config.colorPreview then
				local bgColor, bgColorC = utilitools.files.beattools.easing.getEase("ease", "bgColor", cs.editorBeat, nil, nil)
				local voidColor, voidColorC = utilitools.files.beattools.easing.getEase("ease", "voidColor", cs.editorBeat, nil, nil)
				local outline, outlineC = utilitools.files.beattools.easing.getEase("ease", "outline", cs.editorBeat, nil, nil)
				local bgNoise, bgNoiseC = utilitools.files.beattools.easing.getEase("ease", "vfx.bgNoise", cs.editorBeat, nil, nil)
				local bgNoiseColor, bgNoiseColorC = utilitools.files.beattools.easing.getEase("ease", "vfx.bgNoiseColor", cs.editorBeat, nil, nil)
				local hom, homC = utilitools.files.beattools.easing.getEase("ease", "vfx.hom", cs.editorBeat, nil, nil)

				local faceColor, faceColorC = utilitools.files.beattools.easing.getEase("ease", "p.faceColor", cs.editorBeat, nil, nil)
				local fillColor, fillColorC = utilitools.files.beattools.easing.getEase("ease", "p.fillColor", cs.editorBeat, nil, nil)
				local outlineColor, outlineColorC = utilitools.files.beattools.easing.getEase("ease", "p.outlineColor", cs.editorBeat, nil, nil)

				local songName, songNameC = utilitools.files.beattools.easing.getEase("songNameOverride", nil, cs.editorBeat, nil, nil)
				for i = 1, 8 do
					local col, colC = utilitools.files.beattools.easing.getEase("setColor", i - 1, cs.editorBeat, nil, nil)
					if col then
						local ColorButtonPos = imgui.GetCursorScreenPos()
						local additionalInfo = ""

						if not hom.value then
							if bgColor.value == i - 1 then
								additionalInfo = additionalInfo .. "\nBackground Color"
							end
							if voidColor.value == i - 1 then
								additionalInfo = additionalInfo .. "\nVoid Color"
							end
						end
						if outline.value ~= nil and outline.value == i - 1 then
							additionalInfo = additionalInfo .. "\nOutline"
						end
						if bgNoise.value ~= 0 and bgNoise.value ~= 1 and bgNoiseColor.value == i - 1 then
							additionalInfo = additionalInfo .. "\nNoise (" .. (helpers.round(bgNoise.value * 1e3) / 1e1) .. "%)"
						end
						if faceColor.value == i - 1 then
							additionalInfo = additionalInfo .. "\nPlayer Face Color"
						end
						if fillColor.value == i - 1 then
							additionalInfo = additionalInfo .. "\nPlayer Fill Color"
						end
						if outlineColor.value == i - 1 then
							additionalInfo = additionalInfo .. "\nPlayer Outline Color"
						end

						imgui.ColorButton(
							"Color channel " .. i - 1 .. " (" .. colC.r.index .. "/" .. colC.r.total .. " " .. colC.g.index .. "/" .. colC.g.total .. " " .. colC.b.index .. "/" .. colC.b.total .. " events)" .. additionalInfo,
							imgui.ImVec4_Float(love.math.colorFromBytes(col.r, col.g, col.b, 255)),
							2^1,
							imgui.ImVec2_Float(20, 20)
						)
						if imgui.IsItemClicked(0) then utilitools.files.beattools.easing.select("setColor", i - 1) end
						if imgui.IsItemClicked(1) then utilitools.string.toClipboard(beattools.rgb2hex(col.r, col.g, col.b)) end
						if imgui.IsItemClicked(2) then
							self.placeEvent = "beattoolsEvent;setColor;color," .. i - 1 .. ",number;r," .. col.r .. ",number;g," .. col.g .. ",number;b," .. col.b .. ",number"
						end

						if mods.beattools.config.colorEasePreview then
							if not hom.value then
								if bgColor.value == i - 1 then
									imgui.SetCursorScreenPos(imgui.ImVec2_Float(ColorButtonPos.x, ColorButtonPos.y))
									imgui.Image(sprites.editor.events.setbgcolor, imgui.ImVec2_Float(10, 10))
								end
								if voidColor.value == i - 1 then
									imgui.SetCursorScreenPos(imgui.ImVec2_Float(ColorButtonPos.x + 10, ColorButtonPos.y))
									imgui.Image(sprites.editor.events.setbgcolor, imgui.ImVec2_Float(10, 10), nil, nil, imgui.ImVec4_Float(1, 1, 1, 0.5))
								end
							end
							if outline.value ~= nil and outline.value == i - 1 then
								imgui.SetCursorScreenPos(imgui.ImVec2_Float(ColorButtonPos.x, ColorButtonPos.y + 10))
								imgui.Image(sprites.editor.events.outline, imgui.ImVec2_Float(10, 10))
							end
							if bgNoise.value ~= 0 and bgNoise.value ~= 1 and bgNoiseColor.value == i - 1 then
								imgui.SetCursorScreenPos(imgui.ImVec2_Float(ColorButtonPos.x + 10, ColorButtonPos.y + 10))
								imgui.Image(sprites.editor.events.noise, imgui.ImVec2_Float(10, 10))
							end
						end

						imgui.SetCursorScreenPos(imgui.ImVec2_Float(ColorButtonPos.x + 25, ColorButtonPos.y))
					end
				end
				imgui.SameLine()
				local additionalInfo = ""
				if faceColor.value == -1 then
					if additionalInfo ~= "" then additionalInfo = additionalInfo .. "\n" end
					additionalInfo = additionalInfo ..  "Player Face Color (Original Face Colors)"
				end
				if songName.newname then
					if additionalInfo ~= "" then additionalInfo = additionalInfo .. "\n" end
					additionalInfo = additionalInfo ..  "Song Name (" .. songName.newname .. ") "
				end
				if additionalInfo ~= "" then
					imgui.Text("[+]")
					utilitools.imguiHelpers.tooltip(additionalInfo)
				else
					imgui.NewLine()
				end
			end
			if mods.beattools.config.coordsDisplay then
				imgui.TextUnformatted("X/Y: " .. helpers.round(mouse.rx) .. "/" ..  helpers.round(mouse.ry))
			end
			if mods.beattools.config.editorMenu then
				if utilitools.files.beattools.config then utilitools.files.beattools.config() end
				if self.zoom then
					if self.zoom < mods.beattools.config.zoomMin then self.zoom = mods.beattools.config.zoomMin end
					if self.zoom > mods.beattools.config.zoomMax then self.zoom = mods.beattools.config.zoomMax end
					self.drawDistance = mods.beattools.config.editorBeats
					self.angleSnapValues = mods.beattools.config.angleSnapValues
					self.beatSnapValues = mods.beattools.config.beatSnapValues
				end
			end

			imgui.End()
		end
	end
	if mods.beattools.config.imguiGuide then
		helpers.SetNextWindowPos(750, 420, window_flag)
		helpers.SetNextWindowSize(200, 300, window_flag)
		imgui.ShowDemoWindow()
	end
	if mods.beattools.config.editorCalculator and utilitools.files.beattools.calculator then
		utilitools.files.beattools.calculator(window_flag, inputFlag)
	end
	if mods.beattools.config.undoHistory and utilitools.files.beattools.undoHistory then
		utilitools.files.beattools.undoHistory(window_flag, inputFlag)
	end
end
'''
position = "before"
target = "states/Editor.lua"
