[manifest]
dump_lua = true
priority = 2147483643 # 2147483647 - 4
version = "1.0.0"

# Update self ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''st:setUpdate(function(self, dt)'''
payload = '''
	if self.editMode then
		local timeNow = love.timer.getTime()
		--[[if beattools.playerSprite == "idle" then
			if timeNow - beattools.lastSpriteChange > 8 - 0.1 then
				beattools.playerSprite = "closed"
				beattools.lastSpriteChange = timeNow
			end
		elseif beattools.playerSprite == "closed" then
			if timeNow - beattools.lastSpriteChange > 0.1 then
				beattools.playerSprite = "idle"
				beattools.lastSpriteChange = timeNow
			end
		else]]if beattools.playerSprite == "><" then
			if timeNow - beattools.lastSpriteChange > 1 then
				beattools.playerSprite = "idle"
				beattools.lastSpriteChange = timeNow
			end
		end
		local currentSprite
		if mods.beattools.config.currentSprite then
			currentSprite = utilitools.files.beattools.easing.getEase("forcePlayerSprite", nil, cs.editorBeat, nil, nil)
		end

		-- Penta: This code is not optimised, but it doesnt have to be, "lively cranky" is just for fun
		if mods.beattools.config.livelyCranky and beattools.playerSprite == "><" then
			self.p.forceSprite = beattools.playerSprite
		elseif mods.beattools.config.livelyCranky and maininput:down("modifier") then
			self.p.forceSprite = "happy"
		else
			local forcedSprite = false
			if mods.beattools.config.currentSprite and currentSprite.spriteName ~= "" then
				local spriteName = currentSprite.spriteName
				if spriteName:sub(-4):lower() == ".png" then
					local filename = cLevel .. spriteName
					if love.filesystem.exists(filename) then
						local modTime = love.filesystem.getInfo(cLevel .. spriteName, "file").modtime
						if beattoolsPlayerSpriteChanged[spriteName] ~= modTime then
							beattoolsLastSpriteModified = timeNow
							beattoolsPlayerSpriteChanged[spriteName] = modTime
						end
						if cs.p.spr[spriteName] == nil or timeNow - beattoolsLastSpriteModified > 1 then
							cs.p.spr[spriteName] = love.graphics.newImage(filename)
						end
					end
				end

				if ({ [""] = true, none = true, idle = true, happy = true, miss = true, ["><"] = true, [":3"] = true })[spriteName] or cs.p.spr[spriteName] ~= nil then
					cs.p.forceSprite = spriteName
					cs.p.useFaceStencil = currentSprite.useFaceStencil
					forcedSprite = true
				end
			end
			if not forcedSprite then
				--[[if mods.beattools.config.livelyCranky and timeNow - ((#beattoolsChangeList > 0 and beattoolsChangeList[#beattoolsChangeList].time) or 0) > 60 then
					self.p.forceSprite = "sleep"
				else]]if mods.beattools.config.livelyCranky then
					self.p.forceSprite = beattools.playerSprite
				else
					self.p.forceSprite = ""
				end
			end
		end
	end
'''
position = "after"
target = "states/Editor.lua"

# Tag and blueprint compatibility without Editor Shortcuts ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''for i, v in ipairs(tagEvents) do
	v.time = v.time - self.multiselectStartBeat
end'''
payload = '''
if mods.beattools.config.fakeRepeat then
	for i = #tagEvents, 1, -1 do
		local v = tagEvents[i]
		if v.beattoolsRepeatChild ~= nil then
			table.remove(tagEvents, i)
		end
	end
end
for i = 1, #tagEvents do
	local v = tagEvents[i]
	v.time = v.time - (self.multiselectStartBeat or self.selectedEvent.time)
	if mods.beattools.config.fakeRepeat then
		if v.beattoolsRepeatParent and v.repeats ~= nil and v.repeats > 0 and not utilitools.files.beattools.eventVisuals.hasRepeat[v.type] then
			for i = 1, v.repeats do
				local newEvent = helpers.copy(v)

				newEvent.beattoolsRepeatParent, newEvent.repeats, newEvent.repeatDelay = nil, nil, nil
				newEvent.time = v.time + i * (v.repeatDelay or 1)
				newEvent.beattoolsRepeatChild = v.beattoolsRepeatParent

				table.insert(tagEvents, 1, newEvent)
				i = i + 1
			end
		else
			v.beattoolsRepeatParent = nil
		end
	end
end
'''
position = "at"
target = "states/Editor.lua"

# Dont save parameters ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
# [[patches]]
# [patches.pattern]
# match_indent = true
# pattern = '''v.play_onBeat = nil'''
# payload = '''
# -- Penta:
# -- here's where i would remove parameters i didnt want save in the level files
# -- IF I HAD SOME!!! :(   /ref
# '''
# position = "after"
# target = "obj/LevelManager.lua"
