[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

# Bookmark dragging ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''elseif self.currentlyDragging == "timelineSlider" then'''
payload = '''
elseif self.currentlyDragging == "timelineSlider" and mods.beattools.config.betterBookmarks then
	-- Penta: the bookmark code is so confusing ill just write my own
	utilitools.files.beattools.betterBookmarks.calc()
'''
position = "before"
target = "states/Editor.lua"
times = 1

# Bookmark angle getting ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''local cAngle = 2 * math.pi * (self.editorBeat - currBookmarkBeat) / (nextBookmarkBeat - currBookmarkBeat)'''
payload = '''
local currentBookmark, count, hasPrev, prevBookmark, hasNext, nextBookmark, currentProgress
local cAngle
if mods.beattools.config.betterBookmarks then
	currentBookmark, count, hasPrev, prevBookmark, hasNext, nextBookmark, currentProgress = utilitools.files.beattools.betterBookmarks.getProgress()
	if not currentBookmark or not count or not currentProgress then
	else
		cAngle = 2 * math.pi * currentProgress
	end
end
cAngle = cAngle or 2 * math.pi * (self.editorBeat - currBookmarkBeat) / (nextBookmarkBeat - currBookmarkBeat)
'''
position = "at"
target = "states/Editor.lua"

# Bookmark Visuals ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''love.graphics.printf(sectionName, project.res.cx - 499, project.res.cy - 60, 1000, "center")'''
payload = '''
if not mods.beattools.config.betterBookmarks or not currentBookmark or not count or not currentProgress then
	love.graphics.printf(sectionName, project.res.cx - 499, project.res.cy - 60, 1000, "center")
else
	local text = (self.editorBeat == currentBookmark.time and hasPrev and prevBookmark and (prevBookmark.name .. " >> ") or "") .. currentBookmark.name .. " (" .. count.index .. "/" .. count.total .. ")"
	love.graphics.printf(text, project.res.cx - 499, project.res.cy - 60, 1000, "center")
	if mods.beattools.config.betterBookmarks and currentBookmark.description ~= nil and currentBookmark.description ~= "" then
		love.graphics.printf(currentBookmark.description, project.res.cx - 499, project.res.cy + 60 - 10, 1000, "center")
	end
end
'''
position = "at"
target = "states/Editor.lua"
times = 1

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''love.graphics.circle("fill", project.res.cx, project.res.cy, self:beatToRadius(self.editorBeat))'''
payload = '''
if not mods.beattools.config.betterBookmarks or not currentBookmark or not count or not currentProgress then
else
	love.graphics.setColor(love.math.colorFromBytes(currentBookmark.r, currentBookmark.g, currentBookmark.b, 255))
	love.graphics.arc("line", "open", project.res.cx, project.res.cy, self:beatToRadius(self.editorBeat), 0, 2 * math.pi, 100)
end
'''
position = "after"
target = "states/Editor.lua"
times = 1

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
local textWidth = love.graphics.getFont():getWidth(tostring(math.floor(self.editorBeat)))
love.graphics.draw(sprites.editor.beaticon, project.res.cx - textWidth / 2 - 5.5, project.res.cy - 5)
'''
payload = '''
local beatText, bookmarkBeatText
if not mods.beattools.config.betterBookmarks or not currentBookmark or not count or not currentProgress then
	local textWidth = love.graphics.getFont():getWidth(tostring(math.floor(self.editorBeat)))
	love.graphics.draw(sprites.editor.beaticon, project.res.cx - textWidth / 2 - 5.5, project.res.cy - 5)
else
	beatText = tostring(math.floor(self.editorBeat))
	local textWidth = love.graphics.getFont():getWidth(beatText)

	local bookmarkNextBeat = hasNext and nextBookmark and nextBookmark.time or currentBookmark.time
	bookmarkBeatText = math.floor(self.editorBeat - currentBookmark.time) .. "/" .. math.floor(bookmarkNextBeat - currentBookmark.time)
	local bookmarkBeatTextWidth = love.graphics.getFont():getWidth(bookmarkBeatText)

	if mods.beattools.config.betterBookmarks then
		love.graphics.setColor(love.math.colorFromBytes(currentBookmark.r, currentBookmark.g, currentBookmark.b, 255))
		love.graphics.draw(sprites.editor.bookmarkicon, project.res.cx - bookmarkBeatTextWidth / 2 - 5.5, project.res.cy - 5 + 11)
	else
		love.graphics.draw(sprites.editor.beaticon, project.res.cx - textWidth / 2 - 5.5, project.res.cy - 5)
	end
end
'''
position = "at"
target = "states/Editor.lua"
times = 1

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''love.graphics.printf(math.floor(self.editorBeat), project.res.cx - 18.5, project.res.cy - 7, 50, "center")'''
payload = '''
if not mods.beattools.config.betterBookmarks or not currentBookmark or not count or not currentProgress then
	love.graphics.printf(math.floor(self.editorBeat), project.res.cx - 18.5, project.res.cy - 7, 50, "center")
else
	love.graphics.printf(beatText, project.res.cx - 18.5, project.res.cy - 7, 50, "center")
	love.graphics.printf(bookmarkBeatText, project.res.cx - 18.5, project.res.cy - 7 + 11, 50, "center")
end
'''
position = "at"
target = "states/Editor.lua"
times = 1
