[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

# Ctrl select ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = false
pattern = '''self.selectedEvent = self.level.events[self.overlappingEvents[1]]
end'''
payload = '''		if self.selectedEvent then'''
position = "after"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''self.selectedEvent = self.level.events[v]
-- Changes cursor angle to match event angle
self.cursorAngle = self.selectedEvent.angle'''
payload = '''
if mods.beattools.config.ctrlSelect and self.ctrlSelectPending then
	self:beattoolsCtrlSelect(self.level.events[v])
	self.cursorAngle = self.level.events[v].angle
else
	self.ctrlSelectPending = false
	self:noSelection()
	self.selectedEvent = self.level.events[v]
	-- Changes cursor angle to match event angle
	self.cursorAngle = self.selectedEvent.angle
end
'''
position = "at"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = false
pattern = '''' event. ' .. self.selectedEvent.angle .. '|' .. self.selectedEvent.time,'editor')'''
payload = '''		end'''
position = "after"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''self.lastClickX, self.lastClickY = mouse.rx, mouse.ry'''
payload = '''
self.lastSelected = self.selectedEvent or true
self.ctrlSelectPending = mods.beattools.config.ctrlSelect and utilitools.keybinds.mod.pressed(mods.beattools, "ctrlSelectKey", false)
'''
position = "after"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
function st:SelectEvent()
	self:clearMultiselectVars()
'''
payload = '''
function st:SelectEvent()
	if not mods.beattools.config.ctrlSelect or not utilitools.keybinds.mod.pressed(mods.beattools, "ctrlSelectKey", false) then self:clearMultiselectVars() end
'''
position = "at"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if maininput:down("ctrl") then'''
payload = '''
if mods.beattools.config.ctrlSelect and self.ctrlSelectPending then
	self:beattoolsCtrlSelect(self.level.events[self.overlappingEvents[1]])
elseif (mods.beattools.config.ctrlSelect and maininput:down("c")) or (not mods.beattools.config.ctrlSelect and utilitools.keybinds.mod.pressed(mods.beattools, "ctrlSelectKey", false)) then
'''
position = "at"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''elseif (self.currentlyDragging == "event") and (self.selectedEvent ~= nil) then'''
payload = '''
	self.lastSelected = nil
'''
position = "before"
target = "states/Editor.lua"

# Overlapping ctrl select ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if imgui.Selectable_Bool(Event.info[e.type].name .. ' (ID ' .. v .. ')') then'''
payload = '''
if imgui.Selectable_Bool(
	Event.info[e.type].name .. ' (ID ' .. v .. ')',
	mods.beattools.config.ctrlSelect and self.ctrlSelectPending and self.multiselect and self.multiselect.events and (beatblockPlus2_0Update and bbp.utils.tableContains or tableContains)(self.multiselect.events, self.level.events[v])
) then
'''
position = "at"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if self.deletePending then'''
payload = '''
if mods.beattools.config.ctrlSelect and self.ctrlSelectPending then
	imgui.Text("Select which event to ctrl select:")
elseif self.deletePending then
'''
position = "at"
target = "states/Editor.lua"