[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

# hell.

# End angle setting fix ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(self.selectedEvent, 'decimal', 'time', 'Beat to activate on', { step = beatStep })'''
payload = '''local beattoolsTemp1 = self.selectedEvent.endAngle'''
position = "before"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if imgui.Button('Delete event') then'''
payload = '''
if self.selectedEvent and beattoolsTemp1 == nil and self.selectedEvent.endAngle == 0 then
	utilitools.files.beattools.undo.dontTrack(function()
		self.selectedEvent.endAngle = self.selectedEvent.angle
	end)
end
'''
position = "before"
target = "states/Editor.lua"

# End angle drawing fix ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.regex]
pattern = '''(?<func>self:getPosition)\((?<param>[^\n]+?)\.angle,'''
payload = '''
self:getPosition((mods.beattools.config.displayEndAngle and $param.endAngle or $param.angle),'''
position = "at"
target = "states/Editor.lua"
