[manifest]
dump_lua = true
priority = 2147483643 # 2147483647 - 4
version = "1.0.0"

# Text deco inconsistency fix ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
local function editorDraw(event)
	local pos = cs:getPosition(event.angle,event.time)

	love.graphics.draw(sprites.editor.events.textdeco,pos[1],pos[2],0,1,1,8,8)
end
'''
payload = '''local editorDraw = sprites.editor.events.textdeco'''
position = "at"
target = "levelformat/events/Vfx/textdeco.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
local function editorDraw(event)
	local pos = cs:getPosition(event.angle,event.time)

	love.graphics.draw(sprites.editor.events.advancetextdeco,pos[1],pos[2],0,1,1,8,8)
end
'''
payload = '''local editorDraw = sprites.editor.events.advancetextdeco'''
position = "at"
target = "levelformat/events/Vfx/advancetextdeco.lua"

# Bookmark inconsistency fix ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
local function editorDraw(event)
	local pos = cs:getPosition(event.angle,event.time)

	love.graphics.draw(sprites.editor.events.bookmark,pos[1],pos[2],0,1,1,8,8)
end
'''
payload = '''local editorDraw = sprites.editor.events.bookmark'''
position = "at"
target = "levelformat/events/Editor/bookmark.lua"

# Comment inconsistency fix ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
local function editorDraw(event)
	local pos = cs:getPosition(event.angle,event.time)
	love.graphics.draw(sprites.editor.events.comment,pos[1],pos[2],0,1,1,8,8)
end
'''
payload = '''local editorDraw = sprites.editor.events.comment'''
position = "at"
target = "levelformat/events/Editor/comment.lua"

# Extratap inconsistency fix ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
local function editorDraw(event)
	local pos = cs:getPosition(event.angle,event.time)

	love.graphics.draw(sprites.editor.events.extratap,pos[1],pos[2],0,1,1,8,8)
end
'''
payload = '''local editorDraw = sprites.editor.events.extratap'''
position = "at"
target = "levelformat/events/Notes/extraTap.lua"