[manifest]
dump_lua = true
priority = -2147483643 # -2147483647 + 4
version = "1.0.0"

# Rerouting to beattools event visuals ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
love.graphics.setCanvas(self.layerCanvas.gameplay)
love.graphics.clear()
'''
payload = '''
utilitools.files.beattools.eventVisuals.drawEvents()
--[[
Penta:
Here is where the original event drawing code was
Beattools completely overhauls it
So we can either comment it out or remove it
Removing it will cause lovely warnings when other mods try to patch it
I'll just do both for now?

'''
position = "before"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = false
pattern = '''
	self:drawCursorEvent(self.placeEvent,self.cursorAngle,self.cursorBeat,eventAlpha)
end
'''
payload = '''
		]]
'''
position = "after"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
function st:drawCursorEvent(eventType,angle,time,alpha)
'''
payload = '''
--[[
Penta:
Here is where the original event drawing code was
Beattools completely overhauls it
So we can either comment it out or remove it
Removing it will cause lovely warnings when other mods try to patch it
I'll just do both for now?

'''
position = "before"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
st:setFgDraw(function(self)
'''
payload = ''']]'''
position = "before"
target = "states/Editor.lua"

# Removing redundant original visuals code ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
love.graphics.setCanvas(self.layerCanvas.gameplay)
love.graphics.clear()

love.graphics.setCanvas(self.layerCanvas.vfx)
love.graphics.clear()


for i, v in ipairs(self.level.events) do --draw events
	if Event.info[v.type] and Event.checkActiveRange[v.type](v, self.editorBeat, self.editorBeat + self.drawDistance) then
		local gameplay = Event.info[v.type].gameplayLayer
		if gameplay == nil then
			gameplay = Event.info[v.type].storeInChart
		end
		if gameplay then
			love.graphics.setCanvas(self.layerCanvas.gameplay)
		else
			love.graphics.setCanvas(self.layerCanvas.vfx)
		end
		self:drawEvent(v)

		if self.multiselect then
			for ii, vv in ipairs(self.multiselect.events) do
				if v == vv then
					local pos = self:getPosition(v.angle, v.time)
					love.graphics.draw(sprites.editor.selected, pos[1], pos[2], 0, 1, 1, 11, 11)
				end
			end
		end
	end
end
love.graphics.setCanvas(self.canv)

--draw layers
love.graphics.setColor(1,1,1,0.3)
if self.layers.vfx == 2 then
	love.graphics.draw(self.layerCanvas.vfx)
end
if self.layers.gameplay == 2 then
	love.graphics.draw(self.layerCanvas.gameplay)
end

love.graphics.setColor(1,1,1,1)
if self.layers.vfx == 1 then
	love.graphics.draw(self.layerCanvas.vfx)
end
if self.layers.gameplay == 1 then
	love.graphics.draw(self.layerCanvas.gameplay)
end

--redraw selected event on top
if self.selectedEvent and self.editorBeat <= self.selectedEvent.time then
	local pos = {0, 0}
	if not self.holdEndSelected then
		pos = self:getPosition(self.selectedEvent.angle, self.selectedEvent.time)
	else
		pos = self:getPosition(self.selectedEvent.angle2, self.selectedEvent.time + self.selectedEvent.duration)
	end
	self:drawEvent(self.selectedEvent)
	love.graphics.draw(sprites.editor.selected, pos[1], pos[2], 0, 1, 1, 11, 11)
end


--draw cursor event
if self.placeEvent ~= '' and not imgui.love.GetWantCaptureMouse() then
	local eventAlpha = 0.5
	if self.blockPlacement then
		eventAlpha = 0.25
	end
	self:drawCursorEvent(self.placeEvent,self.cursorAngle,self.cursorBeat,eventAlpha)
end
'''
payload = ''''''
position = "at"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
function st:drawCursorEvent(eventType,angle,time,alpha)
	self:drawEvent({type = eventType, angle = angle, time = time, isCursor = true},alpha)
end
'''
payload = ""
position = "at"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
function st:drawEvent(event,alpha)
	alpha = alpha or 1
	local eventDraw = Event.editorDraw[event.type] or sprites.editor.genericevent


	love.graphics.setColor(1,1,1,alpha)
	if type(eventDraw) == 'function' then
		eventDraw(event, self.editorBeat, self.editorBeat + self.drawDistance)
	else
		local pos = cs:getPosition(event.angle, event.time)
		love.graphics.draw(eventDraw, pos[1], pos[2], 0, 1, 1, 8, 8)
	end

end
'''
payload = ""
position = "at"
target = "states/Editor.lua"
