[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

# Hotkeys ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''function st:checkKeybinds()'''
payload = '''
	if utilitools.keybinds then
		utilitools.keybinds.mod.checkBindsStart()
		utilitools.keybinds.mod.checkBinds(mods.beattools, utilitools.files.beattools.editorKeys)
		utilitools.keybinds.mod.checkBinds(mods.beattools, self.beattoolsEditorKeybinds or {})
		utilitools.keybinds.mod.checkBindsEnd()
		if utilitools.keybinds.mod.lastPressed then return end
		if utilitools.keybinds.listening and utilitools.keybinds.listening.listening then return end
	end
'''
position = "after"
target = "states/Editor.lua"
times = 1

# Text ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''imgui.Text(loc.get("editorKeybinds"))'''
payload = '''utilitools.files.beattools.editorKeysWindow.imgui(loc.get("editorKeybinds"))'''
position = "at"
target = "states/Editor.lua"
times = 1

# Reroute keybinds ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''function st:addKeybind(func, name, k1, k2, k3)'''
payload = '''
	if utilitools.files.beattools.configOptions["editorKeybind " .. name] then
		self.beattoolsEditorKeybinds = self.beattoolsEditorKeybinds or {}
		self.beattoolsEditorKeybinds["editorKeybind " .. name] = func
		return
	end
'''
position = "after"
target = "states/Editor.lua"
times = 1

# Jump ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''end, 'delete selected event', 'delete')'''
payload = '''
-- move to next
self:addKeybind(function ()
	if mods.beattools.config.jumpEvents then
		if self.multiselect then
			local closest = nil
			for i, v in ipairs(self.multiselect.events) do
				if v.time > self.editorBeat and (closest == nil or ((maininput:down("shift") and closest < v.time) or ((not maininput:down("shift")) and closest > v.time))) then closest = v.time end
			end
			if closest ~= nil then self.editorBeat = closest end
		elseif self.selectedEvent then
			self.editorBeat = self.selectedEvent.time
		else
			local closest = nil
			for i, v in ipairs(self.level.events) do
				if ((not mods.beattools.config.fakeRepeat) or v.beattoolsRepeatChild == nil) and not ({ ghost = true, hide = true })[utilitools.files.beattools.eventGroups.eventVisibility(v)] and v.time > self.editorBeat and (closest == nil or ((maininput:down("shift") and closest < v.time) or ((not maininput:down("shift")) and closest > v.time))) then closest = v.time end
			end
			if closest ~= nil then self.editorBeat = closest end
		end
	end
end, "move to next", "ctrl", "move_up")
-- move to previous
self:addKeybind(function ()
	if mods.beattools.config.jumpEvents then
		if self.multiselect then
			local closest = nil
			for i, v in ipairs(self.multiselect.events) do
				if v.time < self.editorBeat and (closest == nil or ((maininput:down("shift") and closest > v.time) or ((not maininput:down("shift")) and closest < v.time))) then closest = v.time end
			end
			if closest ~= nil then self.editorBeat = closest end
		elseif self.selectedEvent then
			self.editorBeat = self.selectedEvent.time
		else
			local closest = nil
			for i, v in ipairs(self.level.events) do
				if ((not mods.beattools.config.fakeRepeat) or v.beattoolsRepeatChild == nil) and not ({ ghost = true, hide = true })[utilitools.files.beattools.eventGroups.eventVisibility(v)] and v.time < self.editorBeat and (closest == nil or ((maininput:down("shift") and closest > v.time) or ((not maininput:down("shift")) and closest < v.time))) then closest = v.time end
			end
			if closest ~= nil then self.editorBeat = closest end
		end
	end
end, "move to previous", "ctrl", "move_down")
'''
position = "after"
target = "states/Editor.lua"
times = 1

# Prevent hotkey + arrows/click overlap ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
# click
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
-- Stops items being placed while ALT is held.

if maininput:down('alt') then
'''
payload = '''
-- Stops items being placed while ALT is held.

-- Penta: prevent keybinds overlap of placing events with:
-- alt select
-- show navigation wheel
if
	maininput:down('alt') or
	utilitools.keybinds.mod.pressed(mods.beattools, "hardCodedEditorKeybind show navigation wheel", true)
then
'''
position = "at"
target = "states/Editor.lua"
times = 1

# arrows
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if (self.deltaTimeCooldown <= 0) and (not maininput:down('alt')) then'''
payload = '''
-- Penta: prevent keybinds overlap of moving events via arrow keys with:
-- move to previous (event)
-- move to next (event)
-- jump to previous section
-- jump to next section
if
	self.deltaTimeCooldown <= 0 and
	not maininput:down('alt') and
	not (mods.beattools.config.jumpEvents and maininput:down("ctrl")) and
	not utilitools.keybinds.mod.pressed(mods.beattools, "hardCodedEditorKeybind jump to previous section", true) and
	not utilitools.keybinds.mod.pressed(mods.beattools, "hardCodedEditorKeybind jump to next section", true)
then
'''
position = "at"
target = "states/Editor.lua"
times = 1

# Custom keybinds rerouting ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
# hardCodedEditorKeybind show navigation wheel
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
if maininput:down('alt') then
	local prevBookmarkBeat, currBookmarkBeat, nextBookmarkBeat = self:findBookmarkBeats()
'''
payload = '''
if utilitools.keybinds.mod.pressed(mods.beattools, "hardCodedEditorKeybind show navigation wheel", true) then
	local prevBookmarkBeat, currBookmarkBeat, nextBookmarkBeat = self:findBookmarkBeats()
'''
position = "at"
target = "states/Editor.lua"
times = 1
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
--draw player
if not maininput:down('alt') then
'''
payload = '''
--draw player
if not utilitools.keybinds.mod.pressed(mods.beattools, "hardCodedEditorKeybind show navigation wheel", true) then
'''
position = "at"
target = "states/Editor.lua"
times = 1
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if maininput:down('alt') or (self.currentlyDragging == "timelineSlider") then'''
payload = '''if utilitools.keybinds.mod.pressed(mods.beattools, "hardCodedEditorKeybind show navigation wheel", true) or (self.currentlyDragging == "timelineSlider") then'''
position = "at"
target = "states/Editor.lua"
times = 1

# hardCodedEditorKeybind jump to previous section
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if maininput:pressed('move_left') and maininput:down('alt') then'''
payload = '''if utilitools.keybinds.mod.pressed(mods.beattools, "hardCodedEditorKeybind jump to previous section", false) then'''
position = "at"
target = "states/Editor.lua"
times = 1

# hardCodedEditorKeybind jump to next section
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''elseif maininput:pressed('move_right') and maininput:down('alt') then'''
payload = '''elseif utilitools.keybinds.mod.pressed(mods.beattools, "hardCodedEditorKeybind jump to next section", false) then'''
position = "at"
target = "states/Editor.lua"
times = 1
