[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

# ... ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.regex]
pattern = '''print\(\' ?'''
payload = "-- print('"
position = "at"
target = "main.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''log('loaded event "'..info.name..'" ('..info.event..eType..')')'''
payload = '''-- log('loaded event "'..info.name..'" ('..info.event..eType..')')'''
position = "at"
target = "obj/GameManager.lua"
times = 1

[[patches]]
[patches.pattern]
match_indent = true
pattern = "print(valueString)"
payload = "print('['..tostring(environment)..'] '..valueString)"
position = "at"
target = "lib/logging.lua"
times = 1

[[patches]]
[patches.pattern]
match_indent = true
pattern = "return log"
payload = '''
log._print = -1

log.display.pq = 0
log.display.steam = 0
'''
position = "before"
target = "lib/logging.lua"
times = 1

[[patches]]
[patches.pattern]
match_indent = true
pattern = "log('loading costume '.. name)"
payload = "-- log('loading costume '.. name)"
position = "at"
target = "obj/Player.lua"
times = 2

[[patches]]
[patches.pattern]
match_indent = true
pattern = 'log("made entity ".. name .." from " ..fname)'
payload = '-- log("made entity ".. name .." from " ..fname)'
position = "at"
target = "lib/entityman.lua"
times = 1

[[patches]]
[patches.pattern]
match_indent = true
pattern = "print('id is ' .. id)"
payload = "-- print('id is ' .. id)"
position = "at"
target = "levelformat/events/Vfx/Deco/deco.lua"
times = 1

[[patches]]
[patches.pattern]
match_indent = true
pattern = 'log("lovebpm end")'
payload = '-- log("lovebpm end")'
position = "at"
target = "lib/lovebpm.lua"
times = 1

[[patches]]
[patches.pattern]
match_indent = true
pattern = "log('level has ' .. #menuItem.variants .. ' variants')"
payload = "-- log('level has ' .. #menuItem.variants .. ' variants')"
position = "at"
target = "states/SongSelect.lua"
times = 1

[[patches]]
[patches.pattern]
match_indent = true
pattern = "print('init colour is ' .. self.colour)"
payload = "-- print('init colour is ' .. self.colour)"
position = "at"
target = "obj/deco/TextDeco.lua"
times = 1

[[patches]]
[patches.pattern]
match_indent = true
pattern = "--load states"
payload = "log:setEnvironment(\"BBP_silent\")"
position = "before"
target = "preload/states.lua"
times = 1

[[patches]]
[patches.pattern]
match_indent = true
pattern = "bs.new('JoystickColorCalibration')"
payload = "log:setEnvironment()"
position = "after"
target = "preload/states.lua"
times = 1
