[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

# Permanent Menus ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''currentSorting = 1'''
payload = '''
currentSorting = mods.beattools.config.persistentSorting and mods.beattools.config.savedSorting or 1
'''
position = "at"
target = "states/SongSelect.lua"
times = 1

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''currentSorting = i'''
payload = '''
mods.beattools.config.savedSorting = i
if mods.beattools.config.persistentSorting then
	utilitools.config.save(mods.beattools)
end
'''
position = "after"
target = "obj/SortingButton.lua"
times = 1
