[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

# Ratemod ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''self.innerOptionsMenu:addNumber('ratemod', self, 'rateMod', 0, 0.1, {0.5, 5}, function() if cs.source then cs.source:setPitch(cs.rateMod) end end)'''
payload = '''self.innerOptionsMenu:addNumber('ratemod', self, 'rateMod', 0, 0.1, mods.beattools.config.rateModLimits and {0.01, 50} or {0.5, 5}, function() if cs.source then cs.source:setPitch(cs.rateMod) end end)'''
position = "at"
target = "states/SongSelect.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''self.innerOptionsMenu:addNumber("ratemod", self, "rateMod", 0, 0.1, { 0.5, 5 }, function() if cs.source then cs.source:setPitch(cs.rateMod) end end)'''
payload = '''self.innerOptionsMenu:addNumber("ratemod", self, "rateMod", 0, 0.1, mods.beattools.config.rateModLimits and { 0.01, 50 } or { 0.5, 5 }, function() if cs.source then cs.source:setPitch(cs.rateMod) end end)'''
position = "at"
target = "states/AtomMap.lua"