[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

# Hide menus ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''self:imgui()'''
payload = '''
if not beattoolsRecordPosition then self:imgui() beattools.randomizeWindows = false end
'''
position = "at"
target = "states/Editor.lua"

# Exit mouse capture ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if self.unsavedChanges then'''
payload = '''
if beattoolsRecordPosition then
	beattoolsRecordPosition = false
	beattoolsRecordFunc = nil
	beattoolsRecordPrecision = 1
elseif self.unsavedChanges then
'''
position = "at"
target = "states/Editor.lua"

# Coordinate copy ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'decimal','y', 'Y position', {step = 1, optional = true, default = project.res.cy})'''
payload = '''
if mods.beattools.config.mouseCoordsButton then
	local pressed = imgui.Button("Use Mouse")
	utilitools.imguiHelpers.tooltip("Copy mouse coordinates")
	if pressed then
		local tempFunc = function ()
			utilitools.prompts.buttons("Choose axis", {
				{ "Both", function ()
					beattoolsRecordPosition = true
					beattoolsRecordFunc = function (x, y) event.x = x event.y = y end
				end },
				{ "X", function ()
					beattoolsRecordPosition = true
					beattoolsRecordFunc = function (x, y) event.x = x end
				end },
				{ "Y", function ()
					beattoolsRecordPosition = true
					beattoolsRecordFunc = function (x, y) event.y = y end
				end }
			})
		end
		utilitools.prompts.buttons("Choose precision", {
			{ "1px", function ()
				beattoolsRecordPrecision = 1
				tempFunc()
			end },
			{ "5px", function ()
				beattoolsRecordPrecision = 5
				tempFunc()
			end },
			{ "10px", function ()
				beattoolsRecordPrecision = 10
				tempFunc()
			end },
			{ "30px", function ()
				beattoolsRecordPrecision = 30
				tempFunc()
			end },
			{ "60px", function ()
				beattoolsRecordPrecision = 60
				tempFunc()
			end },
			{ "90px", function ()
				beattoolsRecordPrecision = 90
				tempFunc()
			end },
			{ "100px", function ()
				beattoolsRecordPrecision = 100
				tempFunc()
			end }
		})
	end
end
'''
position = "after"
target = "levelformat/events/Vfx/deco.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'decimal', 'value', 'Ending value', {step = 0.01, default = 0})'''
payload = '''
if event.var ~= nil then
	local split = utilitools.string.split(event.var, "%.")
	if mods.beattools.config.angleDials and event.var:sub(-2, -1) == ".r" or ({ ["vfx.angleTwist.offset"] = true })[event.var] or (#split > 0 and (split[#split]:lower():find("angle", nil, true) or split[#split]:lower():find("rotate", nil, true))) then
		event.value = utilitools.suggest.dial(event.value, "selectedEventValue", beattools.angleSnap)
	elseif mods.beattools.config.mouseCoordsButton and (event.var:sub(-2, -1) == ".x" or event.var:sub(-2, -1) == ".y") then
		local pressed = imgui.Button("Use Mouse")
		utilitools.imguiHelpers.tooltip("Copy mouse coordinates")
		if pressed then
			local tempFunc = function ()
				beattoolsRecordPosition = true
				beattoolsRecordFunc = function (x, y) event.value = event.var:sub(-2, -1) == ".x" and x or y end
			end
			utilitools.prompts.buttons("Choose precision", {
				{ "1px", function ()
					beattoolsRecordPrecision = 1
					tempFunc()
				end },
				{ "5px", function ()
					beattoolsRecordPrecision = 5
					tempFunc()
				end },
				{ "10px", function ()
					beattoolsRecordPrecision = 10
					tempFunc()
				end },
				{ "30px", function ()
					beattoolsRecordPrecision = 30
					tempFunc()
				end },
				{ "60px", function ()
					beattoolsRecordPrecision = 60
					tempFunc()
				end },
				{ "90px", function ()
					beattoolsRecordPrecision = 90
					tempFunc()
				end },
				{ "100px", function ()
					beattoolsRecordPrecision = 100
					tempFunc()
				end }
			})
		end
	end
end
'''
position = "after"
target = "levelformat/events/Vfx/ease.lua"

# Angle dials ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''imgui.Begin("Event Editor",nil,inputFlag)'''
payload = '''beattools.angleSnap = self.angleSnap ~= 0 and self:getAngleSnapValue() or 360'''
position = "after"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(self.selectedEvent, 'decimal', 'angle', 'Angle to activate at', { step = angleStep })'''
payload = '''if mods.beattools.config.angleDials then self.selectedEvent.angle = utilitools.suggest.dial(self.selectedEvent.angle, "selectedEventAngle", beattools.angleSnap) end'''
position = "after"
target = "states/Editor.lua"

# End angle
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'decimal', 'endAngle', 'Angle to end up at', {step = cs:getAngleStep(), optional = true, default = 0})'''
payload = '''if mods.beattools.config.angleDials and event.endAngle then event.endAngle = utilitools.suggest.dial(event.endAngle, "selectedEventEndAngle", beattools.angleSnap) end'''
position = "after"
target = "levelformat/events/Notes/block.lua"
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'decimal', 'endAngle', 'Angle to end up at', {step = cs:getAngleStep(), optional = true, default = 0})'''
payload = '''if mods.beattools.config.angleDials and event.endAngle then event.endAngle = utilitools.suggest.dial(event.endAngle, "selectedEventEndAngle", beattools.angleSnap) end'''
position = "after"
target = "levelformat/events/Notes/hold.lua"
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'decimal', 'endAngle', 'Angle to end up at', {step = cs:getAngleStep(), optional = true, default = 0})'''
payload = '''if mods.beattools.config.angleDials and event.endAngle then event.endAngle = utilitools.suggest.dial(event.endAngle, "selectedEventEndAngle", beattools.angleSnap) end'''
position = "after"
target = "levelformat/events/Notes/inverse.lua"
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'decimal', 'endAngle', 'Angle to end up at', {step = cs:getAngleStep(), optional = true, default = 0})'''
payload = '''if mods.beattools.config.angleDials and event.endAngle then event.endAngle = utilitools.suggest.dial(event.endAngle, "selectedEventEndAngle", beattools.angleSnap) end'''
position = "after"
target = "levelformat/events/Notes/mine.lua"
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'decimal', 'endAngle', 'Angle to end up at', {step = cs:getAngleStep(), optional = true, default = 0})'''
payload = '''if mods.beattools.config.angleDials and event.endAngle then event.endAngle = utilitools.suggest.dial(event.endAngle, "selectedEventEndAngle", beattools.angleSnap) end'''
position = "after"
target = "levelformat/events/Notes/mineHold.lua"
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'decimal', 'endAngle', 'Angle to end up at', {step = cs:getAngleStep(), optional = true, default = 0})'''
payload = '''if mods.beattools.config.angleDials and event.endAngle then event.endAngle = utilitools.suggest.dial(event.endAngle, "selectedEventEndAngle", beattools.angleSnap) end'''
position = "after"
target = "levelformat/events/Notes/side.lua"
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'decimal', 'endAngle', 'Angle to end up at for initial approach', {step = cs:getAngleStep(), optional = true, default = 0})'''
payload = '''if mods.beattools.config.angleDials and event.endAngle then event.endAngle = utilitools.suggest.dial(event.endAngle, "selectedEventEndAngle", beattools.angleSnap) end'''
position = "after"
target = "levelformat/events/Notes/bounce.lua"
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'decimal', 'endAngle', 'Angle to end up at', {step = cs:getAngleStep(), optional = true, default = 0})'''
payload = '''if mods.beattools.config.angleDials and event.endAngle then event.endAngle = utilitools.suggest.dial(event.endAngle, "selectedEventEndAngle", beattools.angleSnap) end'''
position = "after"
target = "levelformat/events/Advanced/trace.lua"

# Bounce
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'decimal', 'rotation', 'Rotation between bounces', {step = cs:getAngleStep(), default = 0})'''
payload = '''if mods.beattools.config.angleDials then event.rotation = utilitools.suggest.dial(event.rotation, "selectedEventRotation", beattools.angleSnap) end'''
position = "after"
target = "levelformat/events/Notes/bounce.lua"

# Hold
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'decimal', 'angle2', 'Angle for end of the hold', {step = cs:getAngleStep(), default = event.angle})'''
payload = '''if mods.beattools.config.angleDials then event.angle2 = utilitools.suggest.dial(event.angle2, "selectedEventAngle2", beattools.angleSnap) end'''
position = "after"
target = "levelformat/events/Notes/hold.lua"

# Minehold
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'decimal', 'angle2', 'Angle for end of the hold', {step = cs:getAngleStep(), default = event.angle})'''
payload = '''if mods.beattools.config.angleDials then event.angle2 = utilitools.suggest.dial(event.angle2, "selectedEventAngle2", beattools.angleSnap) end'''
position = "after"
target = "levelformat/events/Notes/mineHold.lua"

# Trace
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'decimal', 'angle2', 'Angle for end of the trace', {step = cs:getAngleStep(), default = event.angle})'''
payload = '''if mods.beattools.config.angleDials then event.angle2 = utilitools.suggest.dial(event.angle2, "selectedEventAngle2", beattools.angleSnap) end'''
position = "after"
target = "levelformat/events/Advanced/trace.lua"

# Deco
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'decimal','r', 'Rotation', {step = angleStep, optional = true, default = 0})'''
payload = '''
Event.property(event,'decimal','r', 'Rotation', {step = mods.beattools.config.decoRotation and 1 or angleStep, optional = true, default = 0})
if mods.beattools.config.angleDials and event.r then event.r = utilitools.suggest.dial(event.r, "selectedEventR", beattools.angleSnap) end
'''
position = "at"
target = "levelformat/events/Vfx/deco.lua"

# Paddles
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'int', 'newWidth', 'New width to ease to', {default = 70, optional=true})'''
payload = '''if mods.beattools.config.angleDials and event.newWidth then event.newWidth = utilitools.suggest.dial(event.newWidth, "selectedEventNewWidth", beattools.angleSnap) end'''
position = "after"
target = "levelformat/events/Gameplay/paddles.lua"
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'int', 'newAngle', 'New angle to ease to', {default = 0, optional=true})'''
payload = '''if mods.beattools.config.angleDials and event.newAngle then event.newAngle = utilitools.suggest.dial(event.newAngle, "selectedEventNewAngle", beattools.angleSnap) end'''
position = "after"
target = "levelformat/events/Gameplay/paddles.lua"

# Ease sequence
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(v,'decimal', 'startValue', 'Starting value', {step = 0.01, optional = true, default = 0, uniqueName = 'startValue'..i})'''
payload = '''if mods.beattools.config.angleDials and v.startValue and v.variable == "angle" then v.startValue = utilitools.suggest.dial(v.startValue, "selectedEventStartValue", beattools.angleSnap) end'''
position = "after"
target = "levelformat/events/Vfx/easeSequence.lua"
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(v,'decimal', 'endValue', 'Ending value', {step = 0.01, default = 0, uniqueName = 'endValue'..i})'''
payload = '''if mods.beattools.config.angleDials and v.variable == "angle" then v.endValue = utilitools.suggest.dial(v.endValue, "selectedEventEndValue", beattools.angleSnap) end'''
position = "after"
target = "levelformat/events/Vfx/easeSequence.lua"

# Text deco
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'decimal', 'r', 'Text rotation', {step = 1, optional = true, default = 0})'''
payload = '''if mods.beattools.config.angleDials and event.r then event.r = utilitools.suggest.dial(event.r, "selectedEventR", beattools.angleSnap) end'''
position = "after"
target = "levelformat/events/Vfx/textdeco.lua"
