[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

# Menumusicmanager in editor ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''self.lastEditorBeat = 0'''
payload = '''
self.beattoolsMenuMusicInEditorOn = mods.beattools.config.menuMusicInEditor
if not self.menuMusicManager then
	self.menuMusicManager = em.init("MenuMusicManager")
	self.menuMusicManager:play()
	if not (mods.beattools.config.menuMusicInEditor and savedata.options.audio.playMenuMusic) then
		self.menuMusicManager:stop()
	end
end

'''
position = "before"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''cs = bs.load(returnData.state)'''
payload = '''
if self.menuMusicManager then
	self.menuMusicManager:clearOnBeatHooks()
	self.menuMusicManager:forceUnmute()
	cs.menuMusicManager = self.menuMusicManager
	if not mods.beattools.config.menuMusicInEditor then self.menuMusicManager.music:play() end
end
'''
position = "after"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''st:setUpdate(function(self, dt)'''
payload = '''
	if self.menuMusicManager then
		self.menuMusicManager:update(dt)
		if self.beattoolsMenuMusicInEditorOn ~= mods.beattools.config.menuMusicInEditor then
			if mods.beattools.config.menuMusicInEditor then
				self.menuMusicManager.music:play()
			else
				self.menuMusicManager:stop()
			end
		end
		self.beattoolsMenuMusicInEditorOn = mods.beattools.config.menuMusicInEditor
	end
'''
position = "after"
target = "states/Editor.lua"

# Menumusicmanager in Song Select ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''self.menuMusicManager:stop()
cLevel = filename'''
payload = '''
if self.menuMusicManager and not (mods.beattools.config.menuMusicInEditor and savedata.options.audio.playMenuMusic) then
	self.menuMusicManager:stop()
end
cLevel = filename
'''
position = "at"
target = "states/SongSelect.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''cs = bs.load('Editor')'''
payload = '''
if self.menuMusicManager then
	self.menuMusicManager:clearOnBeatHooks()
	self.menuMusicManager:forceUnmute()
	cs.menuMusicManager = self.menuMusicManager
end
'''
position = "after"
target = "states/SongSelect.lua"

# Inject on playtest ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''function st:playLevel()'''
payload = '''
	beattools.restartBeat = self.startBeat
	if mods.beattools.config.randomizeWindows == "playtest" then beattools.randomizeWindows = true end
	beattools.playerSprite = ""
	self.p.forceSprite = ""
	if self.menuMusicManager and mods.beattools.config.menuMusicInEditor and savedata.options.audio.playMenuMusic then self.menuMusicManager:forceMute() end
'''
position = "after"
target = "states/Editor.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''function st:stopLevel()'''
payload = '''
function st:stopLevel(dontUnmute)
	beattools.playerSprite = "><"
	beattools.lastSpriteChange = love.timer.getTime()
	if not dontUnmute and self.menuMusicManager and mods.beattools.config.menuMusicInEditor and savedata.options.audio.playMenuMusic then
		self.menuMusicManager:forceUnmute()
	end
'''
position = "at"
target = "states/Editor.lua"

# Playtest restart and lagback fix  ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
if maininput:pressed("back") then
	self:stopLevel()
'''
payload = '''
if mods.beattools.config.restartInPlaytest and maininput:pressed("restart") then
	self.pauseBeat = nil
	self:stopLevel(true)

	self.startBeat = beattools.restartBeat
	self:playLevel()
end
if maininput:pressed("back") then
	self.pauseBeat = nil
	self:stopLevel()
'''
position = "at"
target = "states/Editor.lua"