[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

# Adds more splashes ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''-- is cranky real?'''
payload = '''
local additionalSplashes = {
	-- Gotchfutchian
	"Alien crater, Cranky invader!",
	"now thats quality!",
	"Sync your levels!",
	"æ",
	"me witnessing horrors beyond my comprehension {i dont get it}",
	"You never... FREAKING... LISTEEEEEENN!!!!!",
	"Up, down, up, down, beat your lemon-blocks!",
	"Urgh, Curse You!",
	"Give me that block!",
	"I came back to beat the blocks.",
	"candace im sorry",
	"WARNING: Conga Line In Progress!",
	"Reanimate!",
	"Rea! Dy! Get! Set!",
	"One Miss, Too Late, Three Barelies, For Me.",
	":cat2:",
	"You are not in the crankdoers file, this incedent will be reported.",
	"Turn off anti-aliasing!",
	"his name is p.delete you should set him to true",
	[[Whats the song that goes "Waaaa, Waa Waa Waaa"?]],
	"Beatblock goes boop boop beep, somethin' ain't right here!",
	"did someone say it go i heard it go",
	"19,742 bytes!",
	"Don't Hold Back!",
	"Embrace the Spiral!",
	"sevcon these blocks",
	"[font=terminal]I THINK IVE RUN TOO FAR\nI COLLAPSE BY THE[font=main] bed\n[font=main][rotateY=3.2]ZZZ...",
	-- Pentatrate
	"since i have an autoupdating system in place, adding even more splash text is no problem at all",
	"Sponsored by [rotateY=1]Penta's Beattools[rotateY=0]!",
	"Sponsored by [rotateY=1]Beattools[rotateY=0]!",
	"Sponsored by [rotateY=1]Utilitools[rotateY=0]!",
	"This collab is sponsored by Penta's Beattools. Have you ever been in need of things the editor just won't provide ? Well, with Penta's Beattools, many things, such as a particle generator, a bpm corrector, and many more become available to you !\nClick the download link in the description and use code \"WHENP16FL7\" to get 50% off on your first purchase !", -- originally from whenpigfly
	"We won't let the devs take us for fools:\nthis is clearly sponsored by Penta's Beattools.", -- originally from K4kadu
	"Self-advertising is my forte\n- Penta",
	"Oh I'm beating it.\nOh I'm beating it.\nI'm beating my block right now.\nOh I'm beating it.\nOh I'm beating it.\nI'm beating my block right now.",
	"Oh I'm blowing it.\nOh I'm blowing it.\nI'm blowing my fuse right now.\nOh I'm blowing it.\nOh I'm blowing it.\nI'm blowing my fuse right now.",
	"How do you spell \"Nitteuk\"?",
	"Disqualify Bliss",
	"Bliss knows the best way to prepare for a tournament",
	"Are you watching reels?", -- Bliss watched reels in prep for BBT 2025 and lost because of it, who would have thought
	"Hydrogen _Play_ vs coughing Tunne",
	"Update your Beattools, dammit!",
	"Our BEATBLOCK had a saying:\n\"When something Crashes,\nit's usually the Beattools\"",
	"Is it yummy?",
	"Is it done?",
	"I crave progress",
	"Elite ball knowledge",
	"No elite ball knowledge",
	"Want to see penta's balls?\n[offset=50][font=undocrash]Disclaimer: Penta's balls is a shader",
	"\"I have too much decency to be a rich brown color[font=undocrash] (edited)[font=digitalDisco]\ni need not look like a turd\"\n - Mio, looking like a turd",
	"Hows the logic going", -- I'm still not done :'c
	"What the fuck is a drogen",
	"(drogen is german and literally translates to drugs)\n(thats why kak replied in german with straße, which literally translates to road)",
	"\"she shade my balls till I'm penta ?\"\n- Cyt",
	"Shrek in beatblock?",
	"\"I theoretically went to bed around 3 hours ago\"\n- Kakadu",
	"Jumpbeats!",
	"Dshambbeets",
	"Solve your skill issue with a skill solution!",
	"Love cats? I have the right level for you!\n[offset=50][font=undocrash]Ultimate, obviously"
}

_G.beattools = beattools or {}
beattools.splashes = beattools.splashes or {}
beattools.splashes.total = splashes
beattools.splashes.regular = helpers.copy(splashes)
beattools.splashes.additional = additionalSplashes
'''
position = "before"
target = "preload/splashes.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''log(splashes[#splashes])'''
payload = '''
-- +1 for this splash, +1 for the real totals splash
table.insert(additionalSplashes, "There are " .. (#additionalSplashes + 2) .. " beattools modded splashes! Collect them all!")
log(additionalSplashes[#additionalSplashes])

beattools.splashes.added = helpers.copy(splashes)
'''
position = "after"
target = "preload/splashes.lua"

# Adds splashes to splash selector ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''for i = 1, 3 do'''
payload = '''beattools.splashes.rg_nods = helpers.copy(rg_nods)'''
position = "before"
target = "preload/splashes.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
local cranky = {}
if savedata.aprilFools.noCranky then
	--crankless
	cranky = {
'''
payload = '''
	--crankless
	local crankless = {
'''
position = "at"
target = "preload/splashes.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
else
	--crankful
	cranky = {
'''
payload = '''
	--crankful
	local crankful = {
'''
position = "at"
target = "preload/splashes.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
end
for i,v in ipairs(cranky) do
'''
payload = '''
beattools.splashes.crankless = crankless
beattools.splashes.crankful = crankful
for i,v in ipairs(savedata.aprilFools.noCranky and crankless or crankful) do
'''
position = "at"
target = "preload/splashes.lua"

# Adds splashes to randomiser ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if type(num) ~= "number" then num = nil end'''
payload = '''
local splash
if type(num) == "string" then
	splash = num
elseif type(num) ~= "number" then
	num = nil
end
'''
position = "at"
target = "preload/splashes.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
local splash = splashes[num or math.random(#splashes)]

if math.random(1, 8192) == 1 then
'''
payload = '''
if type(num) ~= "string" and num ~= 1 then
	-- num == 1: shiny
	-- num == 2: real total splashes
	-- num <= #splashes + 2: regular + cranky status splashes
	-- num <= #splashes + #additionalSplashes + 2: additional splashes
	if num and (num < 2 or num % 1 ~= 0) then num = nil end -- idiot check
	if mods and mods.beattools and mods.beattools.config and mods.beattools.config.moreSplashes then
		if num and num > #splashes + #additionalSplashes + 2 then num = nil end
		num = num or math.random(#splashes + #additionalSplashes + 2)
		if num == 2 then
			-- +1 for this splash, +1 for the shiny splash, and idk, but its seems ive missed one, ill leave it at 2 though
			splash = "There are actually " .. (#splashes + #additionalSplashes + 2) .. " total modded and vanilla splashes! Collect them all!"
		elseif num <= #splashes + 2 then
			splash = splashes[num - 2]
		else
			splash = additionalSplashes[num - 2 - #splashes]
		end
	else
		if num and num > #splashes + 1 then num = nil end
		splash = splashes[num or math.random(#splashes)]
	end
end
if type(num) ~= "string" and (math.random(1, 8192) == 1 or num == 1) then
'''
position = "at"
target = "preload/splashes.lua"

# Splash selector ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
love.graphics.print(version, project.res.cx * 2 - fonts.digitalDisco:getWidth(version) - 10 ,6 + self.logoY )
color()'''
payload = '''
utilitools.files.beattools.splashes.imgui()
'''
position = "at"
target = "states/Menu.lua"
