[manifest]
dump_lua = true
priority = 1
version = "1.0.0"

# Suggest ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
imgui.InputText(label, numptr, 9999)
if imgui.IsItemDeactivated() then
	event[propertyName] = ffi.string(numptr)
end
'''
payload = '''
if event.type == "ease" and propertyName == "var" then
	event[propertyName] = utilitools.suggest.suggest(ffi.string(numptr), beattools.easeList.eases)
end
if event.type == "setBoolean" and propertyName == "var" then
	event[propertyName] = utilitools.suggest.suggest(ffi.string(numptr), beattools.easeList.bools)
end
'''
position = "after"
target = "obj/GameManager.lua"
