[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

# Suggest ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'string', 'var', 'Variable to ease (must be a child of cs)', {default = ''})'''
payload = '''event.var = utilitools.suggest.suggest(event.var, beattools.easeList.eases)'''
position = "after"
target = "levelformat/events/Vfx/ease.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''Event.property(event,'string', 'var', 'Variable to set (must be a child of cs)', {default = ''})'''
payload = '''event.var = utilitools.suggest.suggest(event.var, beattools.easeList.bools)'''
position = "after"
target = "levelformat/events/Vfx/setBoolean.lua"