[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

# Precise ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
local truncatedResult = math.floor(1000*result+0.5)/1000
local truncatedProperty = math.floor(1000*propertyOld+0.5)/1000
'''
payload = '''
local precision = 3
if mods.beattools.config.preciseInputs then
	precision = 12
end
precision = math.pow(10, precision)
local truncatedResult = math.floor(precision * result + 0.5) / precision
local truncatedProperty = math.floor(precision * propertyOld + 0.5) / precision
'''
position = "at"
target = "obj/GameManager.lua"
times = 1

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''numptr = ffi.new('char[' .. propertyLength .. ']', string.format("%.3f", event[propertyName]))'''
payload = '''
local precision = 3
if mods.beattools.config.preciseInputs then
	precision = utilitools.number.decimals(event[propertyName])
end
numptr = ffi.new('char[' .. propertyLength .. ']', string.format("%." .. precision .. "f", event[propertyName]))
'''
position = "at"
target = "obj/GameManager.lua"
times = 1
